### ISSUE TITLE
Error on searching

### ISSUE THREAD

**Issue by shhossain** [openrecall/openrecall#25]
OS: Windows 11
Python: 3.11(conda)

INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:56:28] "GET /search?q=how+i+met HTTP/1.1" 500 -
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\openrecall\app.py", line 140, in search
    embeddings = [
                 ^
  File "C:\Users\sifat\miniconda3\envs\recall\Lib\site-packages\openrecall\app.py", line 141, in <listcomp>
    np.frombuffer(entry["embedding"], dtype=np.float64) for entry in entries
                  ~~~~~^^^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str

**Comment by ChrisChinh** [comment]
Found out that in newer versions of Python, adding `entry._asdict()['embedding']` instead of `entry['embedding']` fixes the problem, as it allows the namedtuple to be interpreted as a dictionary

**Comment by shhossain** [comment]
@ChrisChinh dot notation also fix the problem.

**Comment by koenvaneijk** [comment]
> newer versions of Python

Do you mean version 3.12 and up?

**Comment by DmacMcgreg** [comment]
Traceback (most recent call last):
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/openrecall/app.py", line 140, in search
    embeddings = [
  File "/Users/d/.pyenv/versions/3.9.19/lib/python3.9/site-packages/openrecall/app.py", line 141, in <listcomp>
    np.frombuffer(entry["embedding"], dtype=np.float64) for entry in entries
TypeError: tuple indices must be integers or slices, not str

Also getting this error on searching

**Comment by ChrisChinh** [comment]
Yes, at least that was the version I was testing on

**Comment by koenvaneijk** [comment]
The `README.md` mentions we currently only support Python 3.11, could you please try that version? Closing this for now, feel free to re-open if issue persists.

**Comment by DmacMcgreg** [comment]
I tested this on 3.11 and got the same error. I copied the fix from the PR and it works.

**Comment by shhossain** [comment]
> The `README.md` mentions we currently only support Python 3.11, could you please try that version? Closing this for now, feel free to re-open if issue persists.

I am facing this problem with python 3.11

**Comment by dmitriyusher** [comment]
> Found out that in newer versions of Python, adding `entry._asdict()['embedding']` instead of `entry['embedding']` fixes the problem, as it allows the namedtuple to be interpreted as a dictionary

This fixed my error in searching, thanks. On Python 3.11 btw
