### ISSUE TITLE
theading.py This Platform is Not Supported 

### ISSUE THREAD

**Issue by ccrow42** [openrecall/openrecall#32]
Feel free to close if this isn't your issue. I'm getting the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ccrow/venv/openrecall/lib/python3.12/site-packages/openrecall/screenshot.py", line 68, in record_screenshots_thread
    active_app_name = get_active_app_name()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccrow/venv/openrecall/lib/python3.12/site-packages/openrecall/utils.py", line 78, in get_active_app_name
    raise NotImplementedError("This platform is not supported")
NotImplementedError: This platform is not supported

This is running on Ubuntu 22.04 with Python 3.12.4 installed from source. Modules are installed in a venv with python3.12 set as the interpreter. 

Doctr was install via the method in the pull request (as the default wasn't working for me)

pip3 install git+https://github.com/koenvaneijk/doctr.git@af711bc04eb8876a7189923fb51ec44481ee18cd

Let me know if you would like further details or if there is anything I can do to help.

**Comment by koenvaneijk** [comment]
New version 0.3 available in `main` should have this fixed. Feel free to re-open if not.
