### ISSUE TITLE
OpenRecall 0.4 - TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by Nox13last** [openrecall/openrecall#36]
Uh-oh, spaghettio.

Windows 11 23H2 (22635.3720)
Python 3.12.4

```C:\Users\[User-Redacted]>python3 -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\app.py", line 7, in <module>
    from openrecall.config import appdata_folder, screenshots_path
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\config.py", line 16, in <module>
    parser.add_argument(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\argparse.py", line 1477, in add_argument
    action = action_class(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'```

**Comment by koenvaneijk** [comment]
@Nox13last thanks for raising this. I pushed a fix to `master`, please try to re-install and re-open this issue if you would face it again!

**Comment by Nox13last** [comment]
Still happening.

```c:\Windows\System32>python -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\site-packages\openrecall\app.py", line 7, in <module>
    from openrecall.config import appdata_folder, screenshots_path
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\site-packages\openrecall\config.py", line 16, in <module>
    parser.add_argument(
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\argparse.py", line 1443, in add_argument
    action = action_class(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'```

**Comment by Nox13last** [comment]
I did, yes. Although as of your comment, the command has pulled 0.5.

It has failed, but for a decidedly different reason. I've made a new ticket for it. #37
