### ISSUE TITLE
OpenRecall 0.5 [WinError 126] The specified module could not be found.

### ISSUE THREAD

**Issue by Nox13last** [openrecall/openrecall#37]
Coming from #36

```c:\Windows\System32>python3 -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\app.py", line 9, in <module>
    from openrecall.nlp import cosine_similarity, get_embedding
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\nlp.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 7, in <module>
    import torch
  File "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\[User-Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.```

**Comment by koenvaneijk** [comment]
Thank you for raising this @Nox13last, have you tried Python 3.11? This is for Python 3.12, which is currently not supported. Please re-open if you face the same issue with Python 3.11.
