### ISSUE TITLE
OpenRecall 0.5 - ValueError: pid must be a positive integer (got -2111540272)

### ISSUE THREAD

**Issue by Nox13last** [openrecall/openrecall#38]
OpenRecall has been running for, I dunno, two hours by this point? The time as of writing is 1:16 pm. The last screenshot was 12:44 pm. I looked over at the console, and this has happened:

```Exception in thread Thread-1 (record_screenshots_thread):
Traceback (most recent call last):
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\openrecall\screenshot.py", line 79, in record_screenshots_thread
    active_app_name = get_active_app_name()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\openrecall\utils.py", line 80, in get_active_app_name
    return get_active_app_name_windows()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\openrecall\utils.py", line 60, in get_active_app_name_windows
    exe = psutil.Process(pid).name()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 323, in __init__
    self._init(pid)
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 334, in _init
    raise ValueError(msg)
ValueError: pid must be a positive integer (got -2111540272)
```

It is apparently still capable of serving screenshots to the UI, but doesn't seem to be creating any new ones.

**Comment by Nox13last** [comment]
I attempted to use the fork at https://github.com/eternnoir/openrecall, and got the same-ish error.
`Exception in thread Thread-1 (record_screenshots_thread):
Traceback (most recent call last):
  File "C:\Users\nox13\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\nox13\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nox13\AppData\Roaming\Python\Python311\site-packages\openrecall\screenshot.py", line 79, in record_screenshots_thread
    active_app_name = get_active_app_name()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nox13\AppData\Roaming\Python\Python311\site-packages\openrecall\utils.py", line 80, in get_active_app_name
    return get_active_app_name_windows()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nox13\AppData\Roaming\Python\Python311\site-packages\openrecall\utils.py", line 60, in get_active_app_name_windows
    exe = psutil.Process(pid).name()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nox13\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 323, in __init__
    self._init(pid)
  File "C:\Users\nox13\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 334, in _init
    raise ValueError(msg)
ValueError: pid must be a positive integer (got -2064514848)`

**Comment by koenvaneijk** [comment]
This is a race condition on Windows. I will push a fix for this later today or tomorrow morning! Stay put!

**Comment by Nox13last** [comment]
Error is now:
```
Exception in thread Thread-1 (record_screenshots_thread):
Traceback (most recent call last):
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\_pswindows.py", line 730, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\_pswindows.py", line 991, in create_time
    user, system, created = cext.proc_times(self.pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from OpenProcess -> ERROR_INVALID_PARAMETER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 359, in _init
    self.create_time()
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 752, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[user-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\_pswindows.py", line 732, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: process no longer exists (pid=674927200)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\site-packages\openrecall\screenshot.py", line 79, in record_screenshots_thread
    active_app_name = get_active_app_name()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\site-packages\openrecall\utils.py", line 80, in get_active_app_name
    return get_active_app_name_windows()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Local\Programs\Python\Python311\Lib\site-packages\openrecall\utils.py", line 60, in get_active_app_name_windows
    exe = psutil.Process(pid).name()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 323, in __init__
    self._init(pid)
  File "C:\Users\[User-Redacted]\AppData\Roaming\Python\Python311\site-packages\psutil\__init__.py", line 372, in _init
    raise NoSuchProcess(pid, msg=msg)
psutil.NoSuchProcess: process PID not found (pid=674927200)
```

**Comment by koenvaneijk** [comment]
I just pushed out version 0.6 which should have fixes for this! Please upgrade 😀

**Comment by Nox13last** [comment]
Done. Will update here if problems persist (or a new ticket if that's preferable).
Can I request that OpenRecall should announce its version number somewhere in the console?

**Comment by koenvaneijk** [comment]
You can check the OpenRecall version number by running `pip show OpenRecall`.
