### ISSUE TITLE
Error when running the app with python3

### ISSUE THREAD

**Issue by silviorodrigues98** [openrecall/openrecall#43]
Hello! I've run the command to install the app, but when i try to run, I get the following error:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\app.py", line 9, in <module>
    from openrecall.nlp import cosine_similarity, get_embedding
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\nlp.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 7, in <module>
    import torch
  File "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\silvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.`

Can someone help me fix it, please?

**Comment by koenvaneijk** [comment]
This can be fixed by downgrading PyTorch==2.2.1 as 2.3.0+ is known to have issues on Windows with shm.dll unfortunately. For now, I've updated the `setup.py` to reflect this. 

Let me know if you still have issues after downgrading.

**Comment by silviorodrigues98** [comment]
Thanks for the answer!

I ve tried to run everything from start again, using the command with the new setup, but got this error:

<img width="868" alt="image" src="https://github.com/openrecall/openrecall/assets/86577914/318ad606-e192-4417-a6d9-b5c7cfb1324e">

**Comment by koenvaneijk** [comment]
Thanks for this, apparently we had to downgrade `torchvision` too. I fixed it now!

**Comment by silviorodrigues98** [comment]
> Thanks for this, apparently we had to downgrade `torchvision` too. I fixed it now!

It worked! Thank you so much, sir! Keep up the good work.
