### ISSUE TITLE
Error loading the program

### ISSUE THREAD

**Issue by LOLLETTU** [openrecall/openrecall#48]
Hi, I tried to run the script and it gave me the following message.
I tried to search in the issues if there was the same error but I didn't find anything, I am newbie :).
I hope to attach enough for someone to be able to help me.
Thank you all! 
```powershell
python3 -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\app.py", line 9, in <module>
    from openrecall.nlp import cosine_similarity, get_embedding
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\nlp.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 7, in <module>
    import torch
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] Impossibile trovare il modulo specificato. Error loading "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

**Comment by koenvaneijk** [comment]
Have you tried downgrading pytorch to 2.2.1?

```
pip install torch==2.2.1
```

**Comment by LOLLETTU** [comment]
I tried but with no success.
I leave you the error.
Thanks for your help.
```powershell
 pip install torch==2.2.1
Collecting torch==2.2.1
  Downloading torch-2.2.1-cp311-cp311-win_amd64.whl.metadata (26 kB)
Requirement already satisfied: filelock in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (4.12.2)
Requirement already satisfied: sympy in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (1.12.1)
Requirement already satisfied: networkx in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (3.3)
Requirement already satisfied: jinja2 in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (3.1.4)
Requirement already satisfied: fsspec in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.2.1) (2024.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinja2->torch==2.2.1) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in c:\users\lollo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sympy->torch==2.2.1) (1.3.0)
Downloading torch-2.2.1-cp311-cp311-win_amd64.whl (198.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 MB 6.9 MB/s eta 0:00:00
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.3.0
    Uninstalling torch-2.3.0:
      Successfully uninstalled torch-2.3.0
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openrecall 0.5 requires torch==2.3.0, but you have torch 2.2.1 which is incompatible.
torchvision 0.18.0 requires torch==2.3.0, but you have torch 2.2.1 which is incompatible.
Successfully installed torch-2.2.1
lollo  ~  ♥ 00:55  python3 -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\app.py", line 10, in <module>
    from openrecall.screenshot import record_screenshots_thread
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\screenshot.py", line 11, in <module>
    from openrecall.ocr import extract_text_from_image
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\ocr.py", line 1, in <module>
    from doctr.models import ocr_predictor
ModuleNotFoundError: No module named 'doctr'
```

**Comment by LOLLETTU** [comment]
> Have you tried downgrading pytorch to 2.2.1?
> 
> ```
> pip install torch==2.2.1
> ```

Nothing changes, 
in the meanwhile i tried to install 3.11.x instead of 3.12.x

**Comment by LOLLETTU** [comment]
> Try pip install doctr
> 
> before running python3 -m openrecall.app

hi! Thanks for your help.
This is the last error that powershell gives to me when i try to run openrecall.
Thanks
```powershell
 python3 -m openrecall.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\app.py", line 9, in <module>
    from openrecall.nlp import cosine_similarity, get_embedding
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\nlp.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 7, in <module>
    import torch
  File "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] Impossibile trovare il modulo specificato. Error loading "C:\Users\lollo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

**Comment by koenvaneijk** [comment]
This is an issue with PyTorch unfortunately. For more information, please check here:
https://discuss.pytorch.org/t/error-loading-lib-site-packages-torch-lib-shm-dll-or-one-of-its-dependencie/201695/9

After downgrading to PyTorch 2.2 this issue should be fixed.

**Comment by LOLLETTU** [comment]
> This is an issue with PyTorch unfortunately. For more information, please check here: https://discuss.pytorch.org/t/error-loading-lib-site-packages-torch-lib-shm-dll-or-one-of-its-dependencie/201695/9
> 
> After downgrading to PyTorch 2.2 this issue should be fixed.

Now i have solved the problem, the script runs! 
Now it tells me connection denied to localhost, i tried to disable firewall but nothing changes.
Thanks
Lorenzo
