### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Holfelix** [openrecall/openrecall#55]
Hi
Thanks for te project. however, as for so many open source projects, the installation or use is neither user friendly nor easy.

this is NOT against the dev but, seemingly, against the open source community itself - is it so hard to create a nice installer, exe file and a nice GUI for an app instead of just saying "install git" and then execute this and this command and then another command to run the app? Why no easy "start menu entry", a nice GUI and nice user interface? most "commercial" developers do this but I see so many open source devs who dont do it and I never understand why.

after running this intsall script for example  I get this error 
>>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\app.py", line 9, in <module>
    from openrecall.nlp import cosine_similarity, get_embedding
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\nlp.py", line 2, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 7, in <module>
    import torch
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.
PS C:\WINDOWS\system32>

even though the "shm.dll" IS in the location requested.

**Comment by koenvaneijk** [comment]
Hi @Holfelix,

I'm sorry to hear your experience was suboptimal. 

Please note this project was only started about a week ago, is created and maintained by volunteers and they are hard at work to improve it. 

It is also released under a free license, in contrast to the "commercial" software you make mention of. 

Your issue has been covered in other issues, if you would have spent half as much time researching as constructing this issue, you would've found a workaround. 

Also, it is on our roadmap to release a one-click installer, something you could've found out quite easily.

I am closing this issue at is a duplicate with other issues. I will leave it as an exercise to the reader to find them.

Kind regard,
Koen
