### ISSUE TITLE
Unable to install on M2 MacBook Air

### ISSUE THREAD

**Issue by mlaaker** [openrecall/openrecall#62]
I've been attempting to install openrecall on my M2 MacBook Air for a couple of weeks, and keep running into issues. I read both https://github.com/openrecall/openrecall?tab=readme-ov-file#get-started and the FAQs but didn't see anything that helped get around this.

When I kick off the installation **$ python3 -m pip install --upgrade --no-cache-dir git+https://github.com/openrecall/openrecall.git** everything seems to install OK… no errors. 

When I then run **$ python3 -m openrecall.app**
I get a "_ModuleNotFoundError: No module named 'tf2onnx'_" so I then **$ pip install tf2onnx** (successfully) and try again

**$ python3 -m openrecall.app**
```
/Users/username/venv-metal/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/username/venv-metal/lib/python3.12/site-packages/openrecall/app.py", line 10, in <module>
    from openrecall.screenshot import record_screenshots_thread
  File "/Users/username/venv-metal/lib/python3.12/site-packages/openrecall/screenshot.py", line 11, in <module>
    from openrecall.ocr import extract_text_from_image
  File "/Users/username/venv-metal/lib/python3.12/site-packages/openrecall/ocr.py", line 3, in <module>
    ocr = ocr_predictor(
          ^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/zoo.py", line 114, in ocr_predictor
    return _predictor(
           ^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/zoo.py", line 32, in _predictor
    det_predictor = detection_predictor(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/detection/zoo.py", line 102, in detection_predictor
    return _predictor(arch, pretrained, assume_straight_pages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/detection/zoo.py", line 50, in _predictor
    _model = detection.__dict__[arch](
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/detection/differentiable_binarization/tensorflow.py", line 396, in db_mobilenet_v3_large
    return _db_mobilenet(
           ^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/detection/differentiable_binarization/tensorflow.py", line 331, in _db_mobilenet
    feat_extractor = IntermediateLayerGetter(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/venv-metal/lib/python3.12/site-packages/doctr/models/utils/tensorflow.py", line 134, in __init__
    intermediate_fmaps = [model.get_layer(layer_name).get_output_at(0) for layer_name in layer_names]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InvertedResidual' object has no attribute 'get_output_at'
```

I've been stuck at this point after reattempting several times to no avail. Hoping there's an easy way to get past this to be able to try openrecall out. Thanks in advance for any pointers.

**Comment by mlaaker** [comment]
When I tried again, running as 'python' instead of 'python3' everything worked fine
