### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by Goddard** [openrecall/openrecall#67]
Got this error

python3 -m openrecall.app                                                                                                              ✔  2m 46s   openrecall  
Downloading https://doctr-static.mindee.com/models?id=v0.7.0/db_mobilenet_v3_large-81e9b152.pt&src=0 to /home/goddard/.cache/doctr/models/db_mobilenet_v3_large-81e9b152.pt
16988160it [00:00, 40674290.86it/s]                                                                                                                                                                               
Downloading https://doctr-static.mindee.com/models?id=v0.3.1/crnn_mobilenet_v3_large_pt-f5259ec2.pt&src=0 to /home/goddard/.cache/doctr/models/crnn_mobilenet_v3_large_pt-f5259ec2.pt
18241536it [00:00, 27423607.08it/s]                                                                                                                                                                               
Appdata folder: /home/goddard/.local/share/openrecall
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8082
INFO:werkzeug:Press CTRL+C to quit
Exception in thread Thread-2 (record_screenshots_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/goddard/projects/openrecall/openrecall/screenshot.py", line 62, in record_screenshots_thread
    last_screenshots = take_screenshots()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/goddard/projects/openrecall/openrecall/screenshot.py", line 50, in take_screenshots
    screenshot = np.array(sct.grab(monitor_))
                          ^^^^^^^^^^^^^^^^^^
  File "/home/goddard/projects/openrecall/env/lib/python3.12/site-packages/mss/base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goddard/projects/openrecall/env/lib/python3.12/site-packages/mss/linux.py", line 427, in _grab_impl
    ximage = self.xlib.XGetImage(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/goddard/projects/openrecall/env/lib/python3.12/site-packages/mss/linux.py", line 229, in _validate
    raise ScreenShotError(f"{func.__name__}() failed", details=details)
mss.exception.ScreenShotError: XGetImage() failed

Operating System: Manjaro Linux 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Kernel Version: 6.8.12-3-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X3D 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X670E AORUS PRO X
System Version: -CF

**Comment by ujetter** [comment]
Hi Goddard,

you need to run it with python 3.11, you are using python 3.12

**Comment by Lockframe** [comment]
> you need to run it with python 3.11, you are using python 3.12 I have added a pull request that handles the issue and stops starting the app.

Strangely, I'm using Python 3.12 and OpenRecall is running fine. If I install the app from your fork, though, then it stops working.

**Comment by ujetter** [comment]
Hi Lockframe,
makes perfectly sense, as the fork checks the python version to be equal to the recommended one in .pythonversion which is 3.11.
So actually this is only checking the prerequisites. If you want you can update 3.12 in pythonversion and you are good to go :-)

**Comment by da2x** [comment]
This is a duplicate of issue #10.
