### ISSUE TITLE
Changing display dimensions causes the worker to fail

### ISSUE THREAD

**Issue by jimsug** [openrecall/openrecall#70]
Or at least, that's what I think is happening. I did also wake from sleep/lock shortly before this, so unclear whether that's what's causing it.

```py
Exception in thread Thread-1 (record_screenshots_thread):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\screenshot.py", line 75, in record_screenshots_thread
    if not is_similar(screenshot, last_screenshot):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\screenshot.py", line 36, in is_similar
    similarity = mean_structured_similarity_index(img1, img2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openrecall\screenshot.py", line 28, in mean_structured_similarity_index
    sigma12 = np.mean((img1_gray - mu1) * (img2_gray - mu2))
                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (2160,3840) (1200,1920)
```

**Comment by Nox13last** [comment]
I have seen this occur if the computer dozes off (and turns my monitors off). Also if I turn a monitor off myself (which makes Windows try to re-enumerate my display devices). If something makes Windows act like a monitor has been unplugged or plugged in, it freaks out.
