### ISSUE TITLE
Fails immediately on first run

### ISSUE THREAD

**Issue by TangentFoxy** [openrecall/openrecall#73]
Looks like one of your dependencies disappeared?

```
Downloading https://doctr-static.mindee.com/models?id=v0.7.0/db_mobilenet_v3_large-81e9b152.pt&src=0 to C:\Users\Tangent\.cache\doctr\models\db_mobilenet_v3_large-81e9b152.pt
Failed download. Trying https -> http instead. Downloading http://doctr-static.mindee.com/models?id=v0.7.0/db_mobilenet_v3_large-81e9b152.pt&src=0 to C:\Users\Tangent\.cache\doctr\models\db_mobilenet_v3_large-81e9b152.pt
Traceback (most recent call last):
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1058, in _send_output
    self.send(msg)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 996, in send
    self.connect()
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1475, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\utils\data.py", line 111, in download_from_url
    _urlretrieve(url, file_path)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\utils\data.py", line 30, in _urlretrieve
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": USER_AGENT})) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1058, in _send_output
    self.send(msg)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 996, in send
    self.connect()
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\http\client.py", line 1475, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\openrecall\app.py", line 10, in <module>
    from openrecall.screenshot import record_screenshots_thread
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\openrecall\screenshot.py", line 11, in <module>
    from openrecall.ocr import extract_text_from_image
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\openrecall\ocr.py", line 3, in <module>
    ocr = ocr_predictor(
          ^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\zoo.py", line 114, in ocr_predictor
    return _predictor(
           ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\zoo.py", line 32, in _predictor
    det_predictor = detection_predictor(
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\detection\zoo.py", line 102, in detection_predictor
    return _predictor(arch, pretrained, assume_straight_pages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\detection\zoo.py", line 50, in _predictor
    _model = detection.__dict__[arch](
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\detection\differentiable_binarization\pytorch.py", line 422, in db_mobilenet_v3_large
    return _dbnet(
           ^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\detection\differentiable_binarization\pytorch.py", line 328, in _dbnet
    load_pretrained_params(model, default_cfgs[arch]["url"], ignore_keys=_ignore_keys)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\models\utils\pytorch.py", line 56, in load_pretrained_params
    archive_path = download_from_url(url, hash_prefix=hash_prefix, cache_subdir="models", **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\utils\data.py", line 116, in download_from_url
    _urlretrieve(url, file_path)
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\site-packages\doctr\utils\data.py", line 30, in _urlretrieve
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": USER_AGENT})) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tangent\scoop\apps\python311\current\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)>
```

**Comment by madcodrr** [comment]
No, I had the same error, just install Python Certs.
