### ISSUE TITLE
Install problem on ubuntu 22.04: No module named 'doctr.models'

### ISSUE THREAD

**Issue by kilmarnock** [openrecall/openrecall#79]
Hi!
I try to install openrecall on ubuntu 22.04. 

I installed openrecall via pip as described in the Readme, now starting `python3 -m openrecall.app
` gives me `ModuleNotFoundError: No module named 'doctr.models'
`
I tried to downgrade pytorch as suggestes elsewhere via `pip install torch==2.2.1` but no success. It outputs `openrecall 0.8 requires torch==2.2.0, but you have torch 2.2.1 which is incompatible.
` , tries to start and still gives the No module named... Error.

Any suggestions?

Full stack trace is 

>  python3 -m openrecall.app
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/openrecall/openrecall/app.py", line 10, in <module>
    from openrecall.screenshot import record_screenshots_thread
  File "/usr/local/src/openrecall/openrecall/screenshot.py", line 11, in <module>
    from openrecall.ocr import extract_text_from_image
  File "/usr/local/src/openrecall/openrecall/ocr.py", line 1, in <module>
    from doctr.models import ocr_predictor
ModuleNotFoundError: No module named 'doctr.models'

**Comment by kilmarnock** [comment]
I switched to ubuntu 24.04.1, installed openrecall in a venv and was able to start it.
