### ISSUE TITLE
ModuleNotFoundError: No module named ‘doctr.models

### ISSUE THREAD

**Issue by christefano** [openrecall/openrecall#85]
Installation on macOS Sequoia went fine. Running `python3 -m openrecall.app` however:

```
% python3 -m openrecall.app
/Users/x/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/x/Library/Python/3.9/lib/python/site-packages/openrecall/app.py", line 10, in <module>
    from openrecall.screenshot import record_screenshots_thread
  File "/Users/x/Library/Python/3.9/lib/python/site-packages/openrecall/screenshot.py", line 11, in <module>
    from openrecall.ocr import extract_text_from_image
  File "/Users/x/Library/Python/3.9/lib/python/site-packages/openrecall/ocr.py", line 1, in <module>
    from doctr.models import ocr_predictor
ModuleNotFoundError: No module named ‘doctr.models'
```

Checking if ocr_predictor is already installed, and it is:

```
x@MacBookPro git % python3 -m pip install ocr_predictor
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ocr_predictor in /Users/x/Library/Python/3.9/lib/python/site-packages (0.2.4)
```

**Comment by jvillegas-revvy** [comment]
same issue with windows 11
