### ISSUE TITLE
Fails to run under Wayland

### ISSUE THREAD

**Issue by kuandai** [openrecall/openrecall#87]
Due to the use of  `xlib` (I believe), it does not appear openrecall functions as intended under Wayland. See log below.
```
$ python3 -m openrecall.app
Downloading https://doctr-static.mindee.com/models?id=v0.7.0/db_mobilenet_v3_large-81e9b152.pt&src=0 to /home/ian/.cache/doctr/models/db_mobilenet_v3_large-81e9b152.pt
16988160it [00:02, 5987947.33it/s]                                              
Downloading https://doctr-static.mindee.com/models?id=v0.3.1/crnn_mobilenet_v3_large_pt-f5259ec2.pt&src=0 to /home/ian/.cache/doctr/models/crnn_mobilenet_v3_large_pt-f5259ec2.pt
18241536it [00:03, 5803398.37it/s]                                              
Appdata folder: /home/ian/.local/share/openrecall
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8082
INFO:werkzeug:Press CTRL+C to quit
Exception in thread Thread-2 (record_screenshots_thread):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ian/.local/lib/python3.12/site-packages/openrecall/screenshot.py", line 67, in record_screenshots_thread
    last_screenshots = take_screenshots()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.12/site-packages/openrecall/screenshot.py", line 54, in take_screenshots
    screenshot = np.array(sct.grab(monitor_))
                          ^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.12/site-packages/mss/base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.12/site-packages/mss/linux.py", line 427, in _grab_impl
    ximage = self.xlib.XGetImage(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.12/site-packages/mss/linux.py", line 229, in _validate
    raise ScreenShotError(f"{func.__name__}() failed", details=details)
mss.exception.ScreenShotError: XGetImage() failed
```

**Comment by quaid** [comment]
I've run into the same error on a fully updated Fedora Linux 41 system, but I have not tested it in legacy Xorg mode.

**Comment by da2x** [comment]
This is a duplicate of issue #10.
